# fvm flutter pub global run melos bootstrap
name: reactive_forms_widgets
packages:
  - packages/**
ignore:
  - "packages/**/example"
  - "packages/reactive_forms_widget_package/**"
  - "packages/.mason"
  - "packages/mason.yaml"
  - "packages/mason-lock.json"